### ISSUE TITLE
Result is not good in LSUN car dataset

### ISSUE THREAD

**Issue by ngocgiang99** [adambielski/perturbed-seg#1]
I trained your source code on LSUN car dataset about 40000 step but result is bad.
I use your setting:
	
> python train.py --max_size 128 --location_jitter 0.125 --min_mask_coverage 0.25 --mask_alpha 2.0 --mixing -d lsun /path/to/lmdb/ --bg_contrast_jitter 0.3 --org_to_crop 1.125 --sched  

This is image generate from generator model : ![image](https://lh3.googleusercontent.com/6OuN_1RckaVG08WcWOHAr8E4Ds8fNjEHSzTyFRDZ4FlNvQn_SKArHuJK8efCIH2hOKX3WjM-NZw1XISZMqAH4yfhidaXjV4WtU_5C4DfpITlcyScik9Bj4xA58AvVyeDWAgNSQV8PFJfQdnvwIt-1mCfyC6hOIAr7w8TtIUrz7kq83HVikifBbkYNuINr3e3lwGwHgm3soEHVi_y8HzUQUIGdxd_Ye8vWDXOXkI77iQxzM-MuluBLBeiOc9vBOh4juuxW_OnRHsg2hcBXDwIbNwkiUWlIOW5I5N1U6z8ZdQacIv2cY8gIkzz9MpbS9wm4Ar4kqlVfigN-MAViWS2vt8ojTIhcWNMu3iFhtvRmmUuWnGBzTnoXeGiwEnLxKJwF5M7NuZsWfMzvzGNZFj4YOi6sKhbFGRYiDIA2TRZRJcnvSkhIgZdNgNo2Wg6dV9o3bDR94jN_YgQzgtM_2Wu1TzoVJW9-I1ovzEhuuwV5HPCEyY1fS7x1mdCm5YQPrRFOBPW3EgxQXXrW60DgtCwYchfDGVs6B39tRrXMjzUBhzoYHpyqWVNHGRQm1Fc1-VZGwVIi00EDIKjrIW75EzqFEuRX6R9JscXgbUzH0P93kyquYPGfPmZsViZrzRiIOvaomaBxE9-IY4tO3950167iQchY7PWBMFboOL5aTIfmWShRhiRNIizSOV55aNC=w530-h134-no)

This is image generate from generator_running model: ![image](https://lh3.googleusercontent.com/UNLeRhtuXnh_4pY400sGKXqE6IFc6pWhHZIvcPBJ70pb8mGHsQLv0WOU2TbET6rniFK40MX9CkfUEMythFwMJCa6hjWVHw-dTzU-2jtXmYiqdpP9O4BXIjr6PQstgGDc1WSYe9rhIGhB_CHW2JSPrc28b5CNj8b7DhdSOT7Ole9Jq6XxlyXUaxOfb9vJ9KRCUFRFVVC9EUqoTUa15J1G8oLUTcCQwu7kxDy0UwEr4itGlSS57ytfqcJ_-IpdOtE-TQ85DSemw97FmNNOKD3FneD_LRpY29IJkFYDiWF3l5K5UXL_x5uY_hMuK8qc5KbPleFl-V_UAy5xe_Sm7bibyZk1Oq0PlUJ_yV5nDRl_rftraVbI7sjchGTkVVSgEnE8HqKu-RjCZ1V2HQGm5fcG3FMrygJala7RfDAtw16aTvqn5hKCuT6u_n_jzWf_9IR8SN7mBjAiAj2iFQmbxnwWXE5fqbOcocDtxcdYk32436lrwUOOcha9lBvWG5maYscyfVEmz5IJf9JkRmYi43mhQjNvLFMZ5yOEC6kdbxP1RhkwS6L1k788mZAphVCVjeWXEbYVowqMwCTvv5BNnzpLg1BnkA_2ub0lJrHkb8eYXZAOLFCQpxSAIQxujaIbSsr8wwfsNC9AvdnQC9XYH8hHm1S2g2EelDOpjNSWnwZG--s9OQZOomBT13p9rqKk=w530-h134-no)

Am i do anything wrong?

**Comment by ttt-ong** [comment]
Hi, l trained this code on LSUN bird dataset
but it has error:
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
Do you know the 'resolution' means in this article? why to change it during training?

**Comment by ttt-ong** [comment]
> I trained your source code on LSUN car dataset about 40000 step but result is bad.
> I use your setting:
> 
> > python train.py --max_size 128 --location_jitter 0.125 --min_mask_coverage 0.25 --mask_alpha 2.0 --mixing -d lsun /path/to/lmdb/ --bg_contrast_jitter 0.3 --org_to_crop 1.125 --sched
> 
> This is image generate from generator model : ![image](https://camo.githubusercontent.com/aa7376711217f636e559494c041cb5f21eec168e/68747470733a2f2f6c68332e676f6f676c6575736572636f6e74656e742e636f6d2f364f754e5f3152636b61564730385763574f484172384534447338664e6a4548537a54794652445a34466c4e76516e5f534b417248754a4b38656643494832684f4b5833576a4d2d4e5a77315849535a4d71414834796668696461586a56345774555f35433444667049546c63795363696b39426a34784135384176567965445741674e5351563850464a6651646e767749742d316d4366794336684f49417237773854744955727a376b7138334856696b696642626b594e75494e723365336c77477748676d33736f454856695f7938487a55515549476478645f596538765744584f586b4937376951787a4d2d4d756c75424c4265694f633976424f68346a757578575f4f6e524873673268634258447749624e776b6955576c494f573549354e3155367a385a6451616349763263593867496b7a7a394d70625339776d344172346b716c566669674e2d4d4156695753327674386f6a54496863574e4d75336946687476526d6d5575576e47427a546e6f5865476977456e4c784b4a7746354d374e755a7357664d7a767a474e5a466a34594f6936734b686246475259694449413254525a524a636e76536b6849675a644e674e6f325767366456396f3362445239346a4e5f5967517a67744d5f32577531547a6f564a57392d49316f767a456875757756354850434579593166533778316d64436d355951507252464f42505733456778515858725736304467744377596368664447567336423339745272584d6a7a5542687a6f594870797157564e484752516d314663312d565a477756496930304544494b6a7249573735457a7146457552583652394a7363586762557a48305039336b79717559504766506d5a7356695a727a5269494f76616f6d61427845392d495934744f333935303136376951636859375057424d46626f4f4c35615449666d575368526869524e49697a534f563535614e433d773533302d683133342d6e6f)
> 
> This is image generate from generator_running model: ![image](https://camo.githubusercontent.com/8a3dfd1bf0796dd916803a936a66f594647f9c5f/68747470733a2f2f6c68332e676f6f676c6575736572636f6e74656e742e636f6d2f554e4c6552687475586e685f34705934303073474b5871453649466336705768485a49766350424a37307062386d474873514c7630574f55325462455436726e69464b34304d5839436b6655454d79746846774d4a436136686a575648772d64547a552d326a74586d596971647050394f344258496a723650517374674744633157535965397268494768425f434857324a5350726332386235434e6a386237446864534f54374f6c65394a713658786c79585561784f666239764a394b524355465246565643394555716f54556131354a3147386f4c55546343517775376b7844793055774572346974476c5353353779746671634a5f2d4970644f74452d545138354453656d773937466d4e4e4f4b4433466e65445f4c5270593239494a6b465944695746336c354b3555584c5f783575595f684d754b387163354b62506c65466c2d565f5541793578655f536d37626962795a6b314f7130506c554a5f7956356e44526c5f726674726156624937736a636847546b56565367456e453848714b752d526a435a3156324851476d3566634733464d7279674a616c61375266444174773136615476716e35684b43755436755f6e5f6a7a57665f39495238534e376d426a4169416a326946516d62786e77575845356671624f636f634474786364596b33323433366c7277554f4f636861396c42765747356d61597363796656456d7a35494a66394a6b526d596934336d68516a4e764c464d5a35794f4543366b646278503152686b7753364c316b3738386d5a4170685643566a655758456259566f77714d774354767635424e6e7a704c6731426e6b415f327562306c4a72486b62386559585a414f4c46435170785341495178756a61496253737238777766734e43394176646e5143395859483868486d315332673245656c444f706a4e53576e775a472d2d73394f515a4f6f6d42543133703972714b6b3d773533302d683133342d6e6f)
> 
> Am i do anything wrong?

Hi, l trained this code on LSUN bird dataset
but it has error:
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
Do you know the 'resolution' means in this article? why to change it during training?

**Comment by yangyu12** [comment]
Hi, @ttt-ong I am trying to run this code on CUB bird dataset. However, this code contains so many errors and it is so difficult to make it work properly. Do you get any positive results yet?

As for your question, I think this is because they use the Progressive GAN or Style GAN, where the resolution gradually increases from 4x4 to 64x64 or higher. Just look at the paper or code.

Progressive GAN: [paper](https://arxiv.org/pdf/1710.10196.pdf)   [code](https://github.com/tkarras/progressive_growing_of_gans)

Style GAN: [paper](https://arxiv.org/pdf/1812.04948.pdf)   [code](https://github.com/NVlabs/stylegan)

**Comment by ttt-ong** [comment]
Thank you! I&nbsp;&nbsp;got the result, maybe your environment is not&nbsp; properly. when l run this code , I only changed the datasets.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "adambielski/perturbed-seg"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月11日(星期二) 晚上10:39
收件人:&nbsp;"adambielski/perturbed-seg"<perturbed-seg@noreply.github.com&gt;;
抄送:&nbsp;"1030120444"<1030120444@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [adambielski/perturbed-seg] Result is not good in LSUN car dataset (#1)





 
Hi, @ttt-ong I am trying to run this code on CUB bird dataset. However, this code contains so many errors and it is so difficult to make it work properly. Do you get any positive results yet?
 
As for your question, I think this is because they use the Progressive GAN or Style GAN, where the resolution gradually increases from 4x4 to 64x64 or higher. Just look at the paper or code.

**Comment by yangyu12** [comment]
Thanks. This code actually works. It was my environment issue. I can obtain decent generated images now.
